# Overrides for opentelemetry-demo Helm chart (https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-demo)
---
observability:
  otelcol:
    enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true

prometheus:
  rbac:
    create: false
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: otel
          static_configs:
            - targets:
                - "otel-demo-otelcol:9464"
        - job_name: otel-collector
          static_configs:
            - targets:
                - "otel-demo-otelcol:8888"
grafana:
  rbac:
    create: false
    pspEnabled: false

# TODO: add resource requests/limits and tolerations for all components here
components:
  adService: {}
  cartService: {}
  checkoutService: {}
  currencyService: {}
  emailService: {}
  featureflagService: {}
  frontend: {}
  frontendProxy:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        memory: 100Mi
  paymentService: {}
  productCatalogService: {}
  quoteService: {}
  recommendationService: {}
  shippingService: {}
