---
observability:
  otelcol:
    enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true

prometheus:
  rbac:
    create: false
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: otel
          static_configs:
            - targets:
                - "otel-demo-otelcol:9464"
        - job_name: otel-collector
          static_configs:
            - targets:
                - "otel-demo-otelcol:8888"
grafana:
  rbac:
    create: false
    pspEnabled: false

# TODO: add resource requests/limits and tolerations for all components here
components:
  adService:
  cartService:
  checkoutService:
  currencyService:
  emailService:
  featureflagService:
  frontend:
  paymentService:
  productcatalogService:
  quoteService:
  recommendationService:
  shippingService:
